CREATE TABLE IF NOT EXISTS T_AUTH
(
CLIENT_ID INT PRIMARY KEY NOT NULL,
AUTH_TOKEN VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS T_DIR
(
DIR_NAME VARCHAR(50) NOT NULL,
DIR_ID SERIAL PRIMARY KEY,
CLIENT_ID INT REFERENCES T_AUTH(CLIENT_ID)
);

CREATE TABLE IF NOT EXISTS T_FILE
(
FILE_NAME VARCHAR(50) NOT NULL,
FILE_ID SERIAL PRIMARY KEY,
CLIENT_ID INT REFERENCES T_AUTH(CLIENT_ID)
);
